# Generated by Django 5.2.7 on 2025-10-22 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iata', models.CharField(max_length=3, unique=True, verbose_name='Código IATA')),
                ('nome', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Assento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Assento')),
                ('classe', models.CharField(choices=[('ECO', 'Econômica'), ('PRE', 'Premium Economy'), ('EXE', 'Executiva')], default='ECO', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=3, unique=True, verbose_name='Código (2-3 letras)')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizador', models.CharField(max_length=8, unique=True)),
                ('status', models.CharField(choices=[('ATV', 'Ativa'), ('CAN', 'Cancelada'), ('EMB', 'Embarcada')], default='ATV', max_length=3)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('assento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='reservas.assento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8, verbose_name='Nº do voo')),
                ('partida', models.DateTimeField()),
                ('chegada', models.DateTimeField()),
                ('preco_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PROG', 'Programado'), ('CANC', 'Cancelado'), ('CONC', 'Concluído')], default='PROG', max_length=4)),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voos', to='reservas.companhiaaerea')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voos_destino', to='reservas.aeroporto')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voos_origem', to='reservas.aeroporto')),
            ],
        ),
        migrations.AddField(
            model_name='assento',
            name='voo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assentos', to='reservas.voo'),
        ),
        migrations.AddConstraint(
            model_name='voo',
            constraint=models.UniqueConstraint(fields=('numero', 'partida'), name='unique_numero_partida'),
        ),
        migrations.AddConstraint(
            model_name='assento',
            constraint=models.UniqueConstraint(fields=('voo', 'codigo'), name='unique_assento_por_voo'),
        ),
    ]
